# This file is part of cjdk-pre-commit.
# Copyright 2022 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.0

  test:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    name: test-${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history needed for setuptools_scm
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox
      - run: nox -s systemtest
